## Real Time Amazon Data

In [ ]:
import http.client
import json
import pandas as pd
import os

In [ ]:
conn = http.client.HTTPSConnection("real-time-amazon-data.p.rapidapi.com")

headers = {
    'x-rapidapi-key': os.environ['x-rapidapi-key'],
    'x-rapidapi-host': "real-time-amazon-data.p.rapidapi.com"
}

search_term = input("Enter the product name: ")

In [41]:
conn.request("GET", "/search?query="+search_term+"&page=1&country=US&sort_by=RELEVANCE&product_condition=ALL&is_prime=false&deals_and_discounts=NONE", headers=headers)

res = conn.getresponse()
api_response_bytes = res.read()

api_response_string = api_response_bytes.decode("utf-8")

data_dict = json.loads(api_response_string)

print(data_dict)

{'status': 'OK', 'request_id': '272cdd82-f2de-437c-bb21-aa8408618038', 'parameters': {'query': 'phone', 'country': 'US', 'sort_by': 'RELEVANCE', 'page': 1, 'is_prime': False, 'language': 'en_US'}, 'data': {'total_products': 148497, 'country': 'US', 'domain': 'www.amazon.com', 'products': [{'asin': 'B0DLHNWHRF', 'product_title': 'Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Blue Black ECOLOGO EPEAT', 'product_price': '$164.99', 'product_original_price': '$199.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 2123, 'product_url': 'https://www.amazon.com/dp/B0DLHNWHRF', 'product_photo': 'https://m.media-amazon.com/images/I/71KGkQ+KOKL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$164.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': True, 'sales_volume': '5K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0DLHLRDBY', 'product_title': 'Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Light Gray ECOLOGO EPEAT', 'product_price': '$164.99', 'product_original_price': '$199.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 2123, 'product_url': 'https://www.amazon.com/dp/B0DLHLRDBY', 'product_photo': 'https://m.media-amazon.com/images/I/71VV0kyOKCL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$164.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': True, 'sales_volume': '3K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0FSKLYZ4Y', 'product_title': '3G Unlocked Mini Phone,XS18 Pro Kids Pocket Phone with Android System, Support Quad Core Dual SIM Face ID (2GB+16GB) (Pink)', 'product_price': '$39.33', 'product_original_price': None, 'currency': 'USD', 'product_star_rating': None, 'product_num_ratings': 0, 'product_url': 'https://www.amazon.com/dp/B0FSKLYZ4Y', 'product_photo': 'https://m.media-amazon.com/images/I/51nhWLd6vWL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$39.33', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': False, 'climate_pledge_friendly': False, 'sales_volume': 'New on Amazon in past month', 'delivery': 'FREE delivery Oct 16 - 22Or fastest delivery Oct 16 - 19', 'has_variations': True}, {'asin': 'B0DP3GH34F', 'product_title': 'SAMSUNG Galaxy S25 Cell Phone, 256GB Smartphone, Unlocked Android, AI Night Mode Camera, Snapdragon 8 Elite Fast Processor, ProScaler Display, 4000mAh Battery, 2025, US 1 Yr Warranty, Silver Shadow ECOLOGO EPEAT', 'product_price': '$659.99', 'product_original_price': '$859.99', 'currency': 'USD', 'product_star_rating': '4.5', 'product_num_ratings': 2942, 'product_url': 'https://www.amazon.com/dp/B0DP3GH34F', 'product_photo': 'https://m.media-amazon.com/images/I/61AeV7RJgYL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$659.99', 'is_best_seller': False, 'is_amazon_choice': True, 'is_prime': True, 'climate_pledge_friendly': True, 'sales_volume': '300+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Overall Pick'}, {'asin': 'B08PP5MSVB', 'product_title': 'Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)', 'product_price': '$205.91', 'product_original_price': '$249.00', 'currency': 'USD', 'product_star_rating': '4.1', 'product_num_ratings': 31657, 'product_url': 'https://www.amazon.com/dp/B08PP5MSVB', 'product_photo': 'https://m.media-amazon.com/images/I/51fYXSnSu9L._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 38, 'product_minimum_offer_price': '$179.00', 'is_best_seller': True, 'is_amazon_choice': False, 'is_prime': False, 'product_availability': 'Only 4 left in stock - order soon.', 'climate_pledge_friendly': False, 'sales_volume': '5K+ bought in past month', 'delivery': 'FREE delivery Thu, Oct 9Or fastest delivery Tomorrow, Oct 8Only 4 left in stock - order soon.', 'has_variations': True, 'product_badge': 'Best Seller'}, {'asin': 'B0CWHXVLXG', 'product_title': 'Motorola Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green', 'product_price': '$139.99', 'product_original_price': '$199.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 3276, 'product_url': 'https://www.amazon.com/dp/B0CWHXVLXG', 'product_photo': 'https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$139.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '2K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0FPG42HT9', 'product_title': '4G mini Smartphone Unlocked for Kids, 4.0 inch HD Display, 3GB RAM+32GB ROM,Dual SIM Dual Camera,Android 10.0,WiFi,Bluetooth,GPS Pocket (Green)', 'product_price': '$58.99', 'product_original_price': None, 'currency': 'USD', 'product_star_rating': '5', 'product_num_ratings': 2, 'product_url': 'https://www.amazon.com/dp/B0FPG42HT9', 'product_photo': 'https://m.media-amazon.com/images/I/61smkpWzKsL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$58.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': False, 'product_availability': 'Only 6 left in stock - order soon.', 'climate_pledge_friendly': False, 'sales_volume': 'New on Amazon in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Thu, Oct 9Only 6 left in stock - order soon.', 'has_variations': True}, {'asin': 'B0DNRK51QQ', 'product_title': 'Motorola Moto G - 2025 | Unlocked | Made for US 4/128GB | 50MP Camera | Forest Gray', 'product_price': '$174.99', 'product_original_price': '$199.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 3276, 'product_url': 'https://www.amazon.com/dp/B0DNRK51QQ', 'product_photo': 'https://m.media-amazon.com/images/I/8160OiLlJEL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$174.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '2K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0BN71X6MF', 'product_title': 'Apple iPhone 14, 128GB, Starlight - Unlocked (Renewed)', 'product_price': '$344.00', 'product_original_price': None, 'currency': 'USD', 'product_star_rating': '4', 'product_num_ratings': 4333, 'product_url': 'https://www.amazon.com/dp/B0BN71X6MF', 'product_photo': 'https://m.media-amazon.com/images/I/51UE4EzWMDL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 23, 'product_minimum_offer_price': '$287.86', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': False, 'product_availability': 'Only 1 left in stock - order soon.', 'climate_pledge_friendly': False, 'sales_volume': '1K+ bought in past month', 'delivery': 'FREE delivery Tomorrow, Oct 8Only 1 left in stock - order soon.', 'has_variations': True}, {'asin': 'B0D1ZFS9GH', 'product_title': 'Motorola Moto G Stylus 5G | 2024 | Unlocked | Made for US 8/256GB | 50MP Camera | Caramel Latte', 'product_price': '$189.98', 'product_original_price': '$399.99', 'currency': 'USD', 'product_star_rating': '4.5', 'product_num_ratings': 1855, 'product_url': 'https://www.amazon.com/dp/B0D1ZFS9GH', 'product_photo': 'https://m.media-amazon.com/images/I/61LE9-6KxdL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$189.98', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '1K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0CP6DDN1H', 'product_title': 'Motorola Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue', 'product_price': '$104.48', 'product_original_price': '$149.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 3276, 'product_url': 'https://www.amazon.com/dp/B0CP6DDN1H', 'product_photo': 'https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$104.48', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '1K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0F7K9LFCL', 'product_title': 'Samsung Galaxy Z Fold7 Cell Phone, 512GB AI Smartphone, Unlocked Android, AI Photo Edits, Large Screen, Long Battery Life, 2025, US 1 Yr Manufacturer Warranty, JetBlack', 'product_price': '$1,719.99', 'product_original_price': '$2,119.99', 'currency': 'USD', 'product_star_rating': '4.5', 'product_num_ratings': 175, 'product_url': 'https://www.amazon.com/dp/B0F7K9LFCL', 'product_photo': 'https://m.media-amazon.com/images/I/61IS7A2f04L._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$1,719.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '200+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0FG1THCD7', 'product_title': 'Samsung Galaxy S25 FE Cell Phone (2025), 256GB AI Smartphone, Unlocked Android, Large Display, 4900mAh Battery, High Res-Camera, AI Photo Edits, Durable, US 1 Yr Warranty, JetBlack', 'product_price': '$544.99', 'product_original_price': '$709.99', 'currency': 'USD', 'product_star_rating': '4.9', 'product_num_ratings': 45, 'product_url': 'https://www.amazon.com/dp/B0FG1THCD7', 'product_photo': 'https://m.media-amazon.com/images/I/61JvXODKxOL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$544.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '500+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0DT4T8D65', 'product_title': 'SAMSUNG Galaxy A16 4G LTE (128GB + 4GB) International Model SM-A165F/DS Factory Unlocked 6.7&quot; Dual Sim 50MP Dual Cam (Case Bundle) (Gray)', 'product_price': '$128.65', 'product_original_price': None, 'currency': 'USD', 'product_star_rating': '4', 'product_num_ratings': 638, 'product_url': 'https://www.amazon.com/dp/B0DT4T8D65', 'product_photo': 'https://m.media-amazon.com/images/I/51Rn-9C6xQL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 7, 'product_minimum_offer_price': '$128.00', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': False, 'climate_pledge_friendly': False, 'sales_volume': '2K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True}, {'asin': 'B0DP96J3KT', 'product_title': 'OnePlus 13R, 12GB RAM + 256GB Storage, Dual-SIM, Unlocked Android Smartphone, Powered by Snapdragon 8 Gen 3, 55W SUPERVOOC Fast Charging, 2025, Nebula Noir', 'product_price': '$499.99', 'product_original_price': '$599.99', 'currency': 'USD', 'product_star_rating': '4.6', 'product_num_ratings': 209, 'product_url': 'https://www.amazon.com/dp/B0DP96J3KT', 'product_photo': 'https://m.media-amazon.com/images/I/71lmumt9z8L._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$499.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': False, 'sales_volume': '500+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}, {'asin': 'B0D7HWJDQM', 'product_title': 'Google Pixel 9 - Unlocked Android Smartphone with Gemini, 24-Hour Battery, Advanced Camera, and 6.3&quot; Actua Display - Obsidian - 128 GB ECOLOGO', 'product_price': '$549.00', 'product_original_price': '$799.00', 'currency': 'USD', 'product_star_rating': '4.5', 'product_num_ratings': 878, 'product_url': 'https://www.amazon.com/dp/B0D7HWJDQM', 'product_photo': 'https://m.media-amazon.com/images/I/61fh21u3DJL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$549.00', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': True, 'sales_volume': '200+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}]}}

In [42]:
# Get first phone data
products_list1 = data_dict['data']['products'][0]
print(products_list1)

{'asin': 'B0DLHNWHRF', 'product_title': 'Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Blue Black ECOLOGO EPEAT', 'product_price': '$164.99', 'product_original_price': '$199.99', 'currency': 'USD', 'product_star_rating': '4.2', 'product_num_ratings': 2123, 'product_url': 'https://www.amazon.com/dp/B0DLHNWHRF', 'product_photo': 'https://m.media-amazon.com/images/I/71KGkQ+KOKL._AC_UY654_FMwebp_QL65_.jpg', 'product_num_offers': 1, 'product_minimum_offer_price': '$164.99', 'is_best_seller': False, 'is_amazon_choice': False, 'is_prime': True, 'climate_pledge_friendly': True, 'sales_volume': '5K+ bought in past month', 'delivery': 'FREE delivery Sun, Oct 12Or fastest delivery Tomorrow, Oct 8', 'has_variations': True, 'product_badge': 'Prime Big Deal'}

In [61]:
## Looping through the data
data = data_dict['data']['products']

print(f"Found {len(data)} products:")

product_list=[]

for product in data:
    asin = product['asin']
    title = product['product_title']
    price = product['product_price']
    product_original_price = product['product_original_price']
    rating = product['product_star_rating']
    produuct_num_ratings = product['product_num_ratings']
    product_num_offers = product['product_num_offers']
    product_original_price = product['product_original_price']
    product_minimum_offer_price = product['product_minimum_offer_price']
    product_url = product['product_url']
    product_photo = product['product_photo']
    product_prime = product['is_prime']
    product_is_best_seller = product['is_best_seller']
    product_is_amazon_choice = product['is_amazon_choice']
    product_badge = product.get('product_badge','N/A')

    # Creating Dictionary
    product_dict = {
        'asin': asin,
        'title': title,
        'price': price,
        'original_price': product_original_price,
        'minimum_offer_price': product_minimum_offer_price,
        'rating': rating,
        'num_of_ratings': produuct_num_ratings,
        'num_of_offers': product_num_offers,
        'url': product_url,
        'photo': product_photo,
        'prime': product_prime,
        'best_seller': product_is_best_seller,
        'amazon_choice': product_is_amazon_choice,
        'product_badge': product_badge
    }

    product_list.append(product_dict)

Found 16 products:

In [62]:
product_list

[{'asin': 'B0DLHNWHRF',
  'title': 'Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Blue Black ECOLOGO EPEAT',
  'price': '$164.99',
  'original_price': '$199.99',
  'minimum_offer_price': '$164.99',
  'rating': '4.2',
  'num_of_ratings': 2123,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0DLHNWHRF',
  'photo': 'https://m.media-amazon.com/images/I/71KGkQ+KOKL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0DLHLRDBY',
  'title': 'Samsung Galaxy A16 5G A Series, Unlocked Android Smartphone, Large AMOLED Display, Durable Design, Super Fast Charging, Expandable Storage, 5G Connectivity, US Version, 2025, Light Gray ECOLOGO EPEAT',
  'price': '$164.99',
  'original_price': '$199.99',
  'minimum_offer_price': '$164.99',
  'rating': '4.2',
  'num_of_ratings': 2123,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0DLHLRDBY',
  'photo': 'https://m.media-amazon.com/images/I/71VV0kyOKCL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0FSKLYZ4Y',
  'title': '3G Unlocked Mini Phone,XS18 Pro Kids Pocket Phone with Android System, Support Quad Core Dual SIM Face ID (2GB+16GB) (Pink)',
  'price': '$39.33',
  'original_price': None,
  'minimum_offer_price': '$39.33',
  'rating': None,
  'num_of_ratings': 0,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0FSKLYZ4Y',
  'photo': 'https://m.media-amazon.com/images/I/51nhWLd6vWL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': False,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'N/A'},
 {'asin': 'B0DP3GH34F',
  'title': 'SAMSUNG Galaxy S25 Cell Phone, 256GB Smartphone, Unlocked Android, AI Night Mode Camera, Snapdragon 8 Elite Fast Processor, ProScaler Display, 4000mAh Battery, 2025, US 1 Yr Warranty, Silver Shadow ECOLOGO EPEAT',
  'price': '$659.99',
  'original_price': '$859.99',
  'minimum_offer_price': '$659.99',
  'rating': '4.5',
  'num_of_ratings': 2942,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0DP3GH34F',
  'photo': 'https://m.media-amazon.com/images/I/61AeV7RJgYL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': True,
  'product_badge': 'Overall Pick'},
 {'asin': 'B08PP5MSVB',
  'title': 'Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)',
  'price': '$205.91',
  'original_price': '$249.00',
  'minimum_offer_price': '$179.00',
  'rating': '4.1',
  'num_of_ratings': 31657,
  'num_of_offers': 38,
  'url': 'https://www.amazon.com/dp/B08PP5MSVB',
  'photo': 'https://m.media-amazon.com/images/I/51fYXSnSu9L._AC_UY654_FMwebp_QL65_.jpg',
  'prime': False,
  'best_seller': True,
  'amazon_choice': False,
  'product_badge': 'Best Seller'},
 {'asin': 'B0CWHXVLXG',
  'title': 'Motorola Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green',
  'price': '$139.99',
  'original_price': '$199.99',
  'minimum_offer_price': '$139.99',
  'rating': '4.2',
  'num_of_ratings': 3276,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0CWHXVLXG',
  'photo': 'https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0FPG42HT9',
  'title': '4G mini Smartphone Unlocked for Kids, 4.0 inch HD Display, 3GB RAM+32GB ROM,Dual SIM Dual Camera,Android 10.0,WiFi,Bluetooth,GPS Pocket (Green)',
  'price': '$58.99',
  'original_price': None,
  'minimum_offer_price': '$58.99',
  'rating': '5',
  'num_of_ratings': 2,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0FPG42HT9',
  'photo': 'https://m.media-amazon.com/images/I/61smkpWzKsL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': False,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'N/A'},
 {'asin': 'B0DNRK51QQ',
  'title': 'Motorola Moto G - 2025 | Unlocked | Made for US 4/128GB | 50MP Camera | Forest Gray',
  'price': '$174.99',
  'original_price': '$199.99',
  'minimum_offer_price': '$174.99',
  'rating': '4.2',
  'num_of_ratings': 3276,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0DNRK51QQ',
  'photo': 'https://m.media-amazon.com/images/I/8160OiLlJEL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0BN71X6MF',
  'title': 'Apple iPhone 14, 128GB, Starlight - Unlocked (Renewed)',
  'price': '$344.00',
  'original_price': None,
  'minimum_offer_price': '$287.86',
  'rating': '4',
  'num_of_ratings': 4333,
  'num_of_offers': 23,
  'url': 'https://www.amazon.com/dp/B0BN71X6MF',
  'photo': 'https://m.media-amazon.com/images/I/51UE4EzWMDL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': False,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'N/A'},
 {'asin': 'B0D1ZFS9GH',
  'title': 'Motorola Moto G Stylus 5G | 2024 | Unlocked | Made for US 8/256GB | 50MP Camera | Caramel Latte',
  'price': '$189.98',
  'original_price': '$399.99',
  'minimum_offer_price': '$189.98',
  'rating': '4.5',
  'num_of_ratings': 1855,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0D1ZFS9GH',
  'photo': 'https://m.media-amazon.com/images/I/61LE9-6KxdL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0CP6DDN1H',
  'title': 'Motorola Moto G Play | 2024 | Unlocked | Made for US 4/64GB | 50MP Camera | Sapphire Blue',
  'price': '$104.48',
  'original_price': '$149.99',
  'minimum_offer_price': '$104.48',
  'rating': '4.2',
  'num_of_ratings': 3276,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0CP6DDN1H',
  'photo': 'https://m.media-amazon.com/images/I/61xk4XNRktL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0F7K9LFCL',
  'title': 'Samsung Galaxy Z Fold7 Cell Phone, 512GB AI Smartphone, Unlocked Android, AI Photo Edits, Large Screen, Long Battery Life, 2025, US 1 Yr Manufacturer Warranty, JetBlack',
  'price': '$1,719.99',
  'original_price': '$2,119.99',
  'minimum_offer_price': '$1,719.99',
  'rating': '4.5',
  'num_of_ratings': 175,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0F7K9LFCL',
  'photo': 'https://m.media-amazon.com/images/I/61IS7A2f04L._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0FG1THCD7',
  'title': 'Samsung Galaxy S25 FE Cell Phone (2025), 256GB AI Smartphone, Unlocked Android, Large Display, 4900mAh Battery, High Res-Camera, AI Photo Edits, Durable, US 1 Yr Warranty, JetBlack',
  'price': '$544.99',
  'original_price': '$709.99',
  'minimum_offer_price': '$544.99',
  'rating': '4.9',
  'num_of_ratings': 45,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0FG1THCD7',
  'photo': 'https://m.media-amazon.com/images/I/61JvXODKxOL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0DT4T8D65',
  'title': 'SAMSUNG Galaxy A16 4G LTE (128GB + 4GB) International Model SM-A165F/DS Factory Unlocked 6.7&quot; Dual Sim 50MP Dual Cam (Case Bundle) (Gray)',
  'price': '$128.65',
  'original_price': None,
  'minimum_offer_price': '$128.00',
  'rating': '4',
  'num_of_ratings': 638,
  'num_of_offers': 7,
  'url': 'https://www.amazon.com/dp/B0DT4T8D65',
  'photo': 'https://m.media-amazon.com/images/I/51Rn-9C6xQL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': False,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'N/A'},
 {'asin': 'B0DP96J3KT',
  'title': 'OnePlus 13R, 12GB RAM + 256GB Storage, Dual-SIM, Unlocked Android Smartphone, Powered by Snapdragon 8 Gen 3, 55W SUPERVOOC Fast Charging, 2025, Nebula Noir',
  'price': '$499.99',
  'original_price': '$599.99',
  'minimum_offer_price': '$499.99',
  'rating': '4.6',
  'num_of_ratings': 209,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0DP96J3KT',
  'photo': 'https://m.media-amazon.com/images/I/71lmumt9z8L._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'},
 {'asin': 'B0D7HWJDQM',
  'title': 'Google Pixel 9 - Unlocked Android Smartphone with Gemini, 24-Hour Battery, Advanced Camera, and 6.3&quot; Actua Display - Obsidian - 128 GB ECOLOGO',
  'price': '$549.00',
  'original_price': '$799.00',
  'minimum_offer_price': '$549.00',
  'rating': '4.5',
  'num_of_ratings': 878,
  'num_of_offers': 1,
  'url': 'https://www.amazon.com/dp/B0D7HWJDQM',
  'photo': 'https://m.media-amazon.com/images/I/61fh21u3DJL._AC_UY654_FMwebp_QL65_.jpg',
  'prime': True,
  'best_seller': False,
  'amazon_choice': False,
  'product_badge': 'Prime Big Deal'}]

In [63]:
# Create DataFrame
product_df = pd.DataFrame(product_list)

In [64]:
product_df.tail()

,asin,title,price,original_price,minimum_offer_price,rating,num_of_ratings,num_of_offers,url,photo,prime,best_seller,amazon_choice,product_badge
11,B0F7K9LFCL,"Samsung Galaxy Z Fold7 Cell Phone, 512GB AI Sm...","$1,719.99","$2,119.99","$1,719.99",4.5,175,1,https://www.amazon.com/dp/B0F7K9LFCL,https://m.media-amazon.com/images/I/61IS7A2f04...,True,False,False,Prime Big Deal
12,B0FG1THCD7,"Samsung Galaxy S25 FE Cell Phone (2025), 256GB...",$544.99,$709.99,$544.99,4.9,45,1,https://www.amazon.com/dp/B0FG1THCD7,https://m.media-amazon.com/images/I/61JvXODKxO...,True,False,False,Prime Big Deal
13,B0DT4T8D65,SAMSUNG Galaxy A16 4G LTE (128GB + 4GB) Intern...,$128.65,None,$128.00,4,638,7,https://www.amazon.com/dp/B0DT4T8D65,https://m.media-amazon.com/images/I/51Rn-9C6xQ...,False,False,False,N/A
14,B0DP96J3KT,"OnePlus 13R, 12GB RAM + 256GB Storage, Dual-SI...",$499.99,$599.99,$499.99,4.6,209,1,https://www.amazon.com/dp/B0DP96J3KT,https://m.media-amazon.com/images/I/71lmumt9z8...,True,False,False,Prime Big Deal
15,B0D7HWJDQM,Google Pixel 9 - Unlocked Android Smartphone w...,$549.00,$799.00,$549.00,4.5,878,1,https://www.amazon.com/dp/B0D7HWJDQM,https://m.media-amazon.com/images/I/61fh21u3DJ...,True,False,False,Prime Big Deal

In [65]:
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   asin                 16 non-null     object
 1   title                16 non-null     object
 2   price                16 non-null     object
 3   original_price       12 non-null     object
 4   minimum_offer_price  16 non-null     object
 5   rating               15 non-null     object
 6   num_of_ratings       16 non-null     int64
 7   num_of_offers        16 non-null     int64
 8   url                  16 non-null     object
 9   photo                16 non-null     object
 10  prime                16 non-null     bool
 11  best_seller          16 non-null     bool
 12  amazon_choice        16 non-null     bool
 13  product_badge        16 non-null     object
dtypes: bool(3), int64(2), object(9)
memory usage: 1.6+ KB

In [66]:
product_df.drop_duplicates(subset='asin', keep='first', inplace=True)

### Fill Null Values

In [67]:
# Filling the Null values in Original prices with current price

product_df['original_price'] = product_df['original_price'].fillna(product_df['price'])

In [68]:
# Filling Null values in Ratings with 0
product_df['rating'] = product_df['rating'].fillna(0)

In [70]:
product_df.isnull().sum()

asin                   0
title                  0
price                  0
original_price         0
minimum_offer_price    0
rating                 0
num_of_ratings         0
num_of_offers          0
url                    0
photo                  0
prime                  0
best_seller            0
amazon_choice          0
product_badge          0
dtype: int64

In [71]:
product_df.head()

,asin,title,price,original_price,minimum_offer_price,rating,num_of_ratings,num_of_offers,url,photo,prime,best_seller,amazon_choice,product_badge
0,B0DLHNWHRF,"Samsung Galaxy A16 5G A Series, Unlocked Andro...",$164.99,$199.99,$164.99,4.2,2123,1,https://www.amazon.com/dp/B0DLHNWHRF,https://m.media-amazon.com/images/I/71KGkQ+KOK...,True,False,False,Prime Big Deal
1,B0DLHLRDBY,"Samsung Galaxy A16 5G A Series, Unlocked Andro...",$164.99,$199.99,$164.99,4.2,2123,1,https://www.amazon.com/dp/B0DLHLRDBY,https://m.media-amazon.com/images/I/71VV0kyOKC...,True,False,False,Prime Big Deal
2,B0FSKLYZ4Y,"3G Unlocked Mini Phone,XS18 Pro Kids Pocket Ph...",$39.33,$39.33,$39.33,0,0,1,https://www.amazon.com/dp/B0FSKLYZ4Y,https://m.media-amazon.com/images/I/51nhWLd6vW...,False,False,False,N/A
3,B0DP3GH34F,"SAMSUNG Galaxy S25 Cell Phone, 256GB Smartphon...",$659.99,$859.99,$659.99,4.5,2942,1,https://www.amazon.com/dp/B0DP3GH34F,https://m.media-amazon.com/images/I/61AeV7RJgY...,True,False,True,Overall Pick
4,B08PP5MSVB,"Apple iPhone 12, 64GB, Black - Fully Unlocked ...",$205.91,$249.00,$179.00,4.1,31657,38,https://www.amazon.com/dp/B08PP5MSVB,https://m.media-amazon.com/images/I/51fYXSnSu9...,False,True,False,Best Seller

In [72]:
len(product_df)

16

### Transforming Data

In [74]:
# Transforming Data
product_df['price'] = product_df['price'].str.replace('$', '')
product_df['minimum_offer_price'] = product_df['minimum_offer_price'].str.replace('$', '')
product_df['original_price'] = product_df['original_price'].str.replace('$', '')

In [75]:
product_df.head()

,asin,title,price,original_price,minimum_offer_price,rating,num_of_ratings,num_of_offers,url,photo,prime,best_seller,amazon_choice,product_badge
0,B0DLHNWHRF,"Samsung Galaxy A16 5G A Series, Unlocked Andro...",164.99,199.99,164.99,4.2,2123,1,https://www.amazon.com/dp/B0DLHNWHRF,https://m.media-amazon.com/images/I/71KGkQ+KOK...,True,False,False,Prime Big Deal
1,B0DLHLRDBY,"Samsung Galaxy A16 5G A Series, Unlocked Andro...",164.99,199.99,164.99,4.2,2123,1,https://www.amazon.com/dp/B0DLHLRDBY,https://m.media-amazon.com/images/I/71VV0kyOKC...,True,False,False,Prime Big Deal
2,B0FSKLYZ4Y,"3G Unlocked Mini Phone,XS18 Pro Kids Pocket Ph...",39.33,39.33,39.33,0,0,1,https://www.amazon.com/dp/B0FSKLYZ4Y,https://m.media-amazon.com/images/I/51nhWLd6vW...,False,False,False,N/A
3,B0DP3GH34F,"SAMSUNG Galaxy S25 Cell Phone, 256GB Smartphon...",659.99,859.99,659.99,4.5,2942,1,https://www.amazon.com/dp/B0DP3GH34F,https://m.media-amazon.com/images/I/61AeV7RJgY...,True,False,True,Overall Pick
4,B08PP5MSVB,"Apple iPhone 12, 64GB, Black - Fully Unlocked ...",205.91,249.00,179.00,4.1,31657,38,https://www.amazon.com/dp/B08PP5MSVB,https://m.media-amazon.com/images/I/51fYXSnSu9...,False,True,False,Best Seller